import type { InstrumentConfig } from '../../types/instrument';

export const drumKitConfig: InstrumentConfig = {
  id: 'drum-kit',
  name: 'Drum Kit',
  pads: [
    {
      id: 'snare',
      label: 'Snare',
      region: { cx: 0.5, cy: 0.72, radius: 0.10 },
      soundFile: '/sounds/snare.wav',
      color: '#ef4444',
      cooldownMs: 80,
      velocityThreshold: 0.4,
      shape: 'drum',
    },
    {
      id: 'hihat',
      label: 'Hi-Hat',
      region: { cx: 0.18, cy: 0.48, radius: 0.07 },
      soundFile: '/sounds/hihat.wav',
      color: '#eab308',
      cooldownMs: 50,
      velocityThreshold: 0.3,
      shape: 'hihat',
    },
    {
      id: 'tom-high',
      label: 'High Tom',
      region: { cx: 0.38, cy: 0.50, radius: 0.08 },
      soundFile: '/sounds/tom-high.wav',
      color: '#3b82f6',
      cooldownMs: 80,
      velocityThreshold: 0.4,
      shape: 'drum',
    },
    {
      id: 'tom-low',
      label: 'Low Tom',
      region: { cx: 0.62, cy: 0.50, radius: 0.08 },
      soundFile: '/sounds/tom-low.wav',
      color: '#a855f7',
      cooldownMs: 80,
      velocityThreshold: 0.4,
      shape: 'drum',
    },
    {
      id: 'crash',
      label: 'Crash',
      region: { cx: 0.22, cy: 0.22, radius: 0.08 },
      soundFile: '/sounds/crash.wav',
      color: '#f97316',
      cooldownMs: 200,
      velocityThreshold: 0.5,
      shape: 'cymbal',
    },
    {
      id: 'ride',
      label: 'Ride',
      region: { cx: 0.78, cy: 0.22, radius: 0.08 },
      soundFile: '/sounds/ride.wav',
      color: '#22c55e',
      cooldownMs: 120,
      velocityThreshold: 0.4,
      shape: 'cymbal',
    },
  ],
};
